import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    brand: "ResQMeal",
    nav_home: "Home", nav_about: "About", nav_contact: "Contact",
    nav_donate: "+ Donate Meal", nav_logout: "Logout", nav_register: "Register", nav_login: "Login",
    hero_label: "LIVE LISTINGS NEAR YOU",
    hero_title1: "Rescue surplus food.",
    hero_title2: "Feed someone today.",
    hero_sub: "Connect with PGs & Hostels to claim free surplus meals before they go to waste. 🍱",
    btn_browse: "Browse Listings →",
    btn_list: "List Surplus Food",
    how_label: "HOW IT WORKS",
    how_title: "Three steps to zero waste",
    listings_label: "AVAILABLE NOW",
    listings_title: "Surplus near you",
    why_label: "WHY RESQMEAL",
    why_title: "Built for India's hostel culture",
    stories_label: "STORIES",
    stories_title: "What people are saying",
    cta_label: "JOIN THE MOVEMENT",
    cta_title: "Every meal rescued",
    cta_green: "matters.",
    cta_sub: "Whether you're a PG owner with leftover food or someone looking for a meal — you belong here.",
    btn_get_started: "Get Started Free →",
    btn_learn: "Learn Our Mission",
    btn_dashboard: "Go to Dashboard →",
    login_welcome: "WELCOME BACK",
    login_title: "Sign in to",
    login_sub: "New here?",
    login_create: "Create an account →",
    login_email: "Email Address",
    login_pass: "Password",
    login_forgot: "Forgot password?",
    login_remember: "Remember me for 30 days",
    login_btn: "Sign In →",
    register_label: "CREATE ACCOUNT",
    register_title: "Join",
    register_sub: "Already have an account?",
    register_signin: "Sign in →",
    search_placeholder: "Search by title or food description…",
    all_locations: "All Locations",
    claim_btn: "Claim Meal →",
    login_to_claim: "Login to Claim →",
    claimed: "✓ Claimed!",
    lang_btn: "Language",
    sidebar_hero: "Hero",
    sidebar_how: "How It Works",
    sidebar_listings: "Listings",
    sidebar_why: "Why Us",
    sidebar_stories: "Stories",
    sidebar_cta: "Join",
    sidebar_theme: "Themes",
    loc_popup_title: "Fill Address",
    loc_popup_sub: "How would you like to fill in your address?",
    loc_auto: "📍 Use My Current Location",
    loc_manual: "✏️ Fill Manually",
    loc_fetching: "Fetching location…",
    loc_error: "Could not fetch location. Please fill manually.",
    city_placeholder: "Search city…",
    phone_placeholder: "Phone number",
    step1: "Basic Info", step2_donor: "PG Details", step2_recv: "Preferences", step3: "Review",
    full_address: "Full Address",
    pg_name: "PG / Hostel Name",
    city_label: "City",
    state_label: "State",
    diet_label: "Typical food type",
    create_account: "Create Account 🎉",
  },
  hi: {
    brand: "ResQMeal",
    nav_home: "होम", nav_about: "हमारे बारे में", nav_contact: "संपर्क",
    nav_donate: "+ भोजन दान करें", nav_logout: "लॉगआउट", nav_register: "रजिस्टर", nav_login: "लॉगिन",
    hero_label: "आपके पास लाइव लिस्टिंग",
    hero_title1: "अतिरिक्त भोजन बचाएं।",
    hero_title2: "आज किसी को खिलाएं।",
    hero_sub: "PG और हॉस्टल के साथ जुड़ें — बर्बाद होने से पहले मुफ्त भोजन लें। 🍱",
    btn_browse: "लिस्टिंग देखें →",
    btn_list: "अतिरिक्त भोजन सूचीबद्ध करें",
    how_label: "यह कैसे काम करता है",
    how_title: "शून्य बर्बादी के तीन कदम",
    listings_label: "अभी उपलब्ध",
    listings_title: "आपके पास अतिरिक्त भोजन",
    why_label: "ResQMeal क्यों",
    why_title: "भारत की हॉस्टल संस्कृति के लिए",
    stories_label: "कहानियाँ",
    stories_title: "लोग क्या कह रहे हैं",
    cta_label: "आंदोलन से जुड़ें",
    cta_title: "हर बचाया भोजन",
    cta_green: "मायने रखता है।",
    cta_sub: "चाहे आप PG मालिक हों या भोजन ढूंढ रहे हों — आप यहाँ के हैं।",
    btn_get_started: "मुफ्त शुरू करें →",
    btn_learn: "हमारा मिशन जानें",
    btn_dashboard: "डैशबोर्ड पर जाएं →",
    login_welcome: "वापस स्वागत है",
    login_title: "साइन इन करें",
    login_sub: "नए यहाँ?",
    login_create: "खाता बनाएं →",
    login_email: "ईमेल पता",
    login_pass: "पासवर्ड",
    login_forgot: "पासवर्ड भूल गए?",
    login_remember: "30 दिनों के लिए याद रखें",
    login_btn: "साइन इन करें →",
    register_label: "खाता बनाएं",
    register_title: "जुड़ें",
    register_sub: "पहले से खाता है?",
    register_signin: "साइन इन करें →",
    search_placeholder: "शीर्षक या भोजन विवरण से खोजें…",
    all_locations: "सभी स्थान",
    claim_btn: "भोजन लें →",
    login_to_claim: "लेने के लिए लॉगिन करें →",
    claimed: "✓ लिया गया!",
    lang_btn: "भाषा",
    sidebar_hero: "मुख्य", sidebar_how: "कैसे", sidebar_listings: "लिस्टिंग",
    sidebar_why: "क्यों", sidebar_stories: "कहानियाँ", sidebar_cta: "जुड़ें",
    sidebar_theme: "थीम",
    loc_popup_title: "पता भरें",
    loc_popup_sub: "अपना पता कैसे भरना चाहेंगे?",
    loc_auto: "📍 वर्तमान स्थान उपयोग करें",
    loc_manual: "✏️ मैन्युअल भरें",
    loc_fetching: "स्थान प्राप्त हो रहा है…",
    loc_error: "स्थान नहीं मिला। कृपया मैन्युअल भरें।",
    city_placeholder: "शहर खोजें…",
    phone_placeholder: "फोन नंबर",
    step1: "बुनियादी जानकारी", step2_donor: "PG विवरण", step2_recv: "प्राथमिकताएं", step3: "समीक्षा",
    full_address: "पूरा पता",
    pg_name: "PG / हॉस्टल का नाम",
    city_label: "शहर",
    state_label: "राज्य",
    diet_label: "भोजन का प्रकार",
    create_account: "खाता बनाएं 🎉",
  },
  mr: {
    brand: "ResQMeal",
    nav_home: "मुखपृष्ठ", nav_about: "आमच्याबद्दल", nav_contact: "संपर्क",
    nav_donate: "+ जेवण दान करा", nav_logout: "लॉगआउट", nav_register: "नोंदणी", nav_login: "लॉगिन",
    hero_label: "तुमच्या जवळ लाइव्ह यादी",
    hero_title1: "अतिरिक्त अन्न वाचवा।",
    hero_title2: "आज कोणाला खाऊ घाला।",
    hero_sub: "PG आणि हॉस्टेलशी जोडा — वाया जाण्यापूर्वी मोफत जेवण घ्या। 🍱",
    btn_browse: "यादी पहा →",
    btn_list: "अतिरिक्त अन्न सूचीबद्ध करा",
    how_label: "हे कसे काम करते",
    how_title: "शून्य बर्बादीसाठी तीन पावले",
    listings_label: "आत्ता उपलब्ध",
    listings_title: "तुमच्या जवळ अतिरिक्त अन्न",
    why_label: "ResQMeal का",
    why_title: "भारताच्या हॉस्टेल संस्कृतीसाठी",
    stories_label: "कहाण्या",
    stories_title: "लोक काय म्हणत आहेत",
    cta_label: "चळवळीत सामील व्हा",
    cta_title: "वाचवलेले प्रत्येक जेवण",
    cta_green: "महत्त्वाचे आहे।",
    cta_sub: "PG मालक असाल किंवा जेवण शोधत असाल — तुमचे स्वागत आहे।",
    btn_get_started: "मोफत सुरू करा →",
    btn_learn: "आमचे ध्येय जाणून घ्या",
    btn_dashboard: "डॅशबोर्डवर जा →",
    login_welcome: "परत आलात!",
    login_title: "साइन इन करा",
    login_sub: "नवीन आहात?",
    login_create: "खाते तयार करा →",
    login_email: "ईमेल पत्ता",
    login_pass: "पासवर्ड",
    login_forgot: "पासवर्ड विसरलात?",
    login_remember: "30 दिवसांसाठी लक्षात ठेवा",
    login_btn: "साइन इन करा →",
    register_label: "खाते तयार करा",
    register_title: "सामील व्हा",
    register_sub: "आधीच खाते आहे?",
    register_signin: "साइन इन करा →",
    search_placeholder: "शीर्षक किंवा अन्न वर्णनाने शोधा…",
    all_locations: "सर्व ठिकाणे",
    claim_btn: "जेवण घ्या →",
    login_to_claim: "घेण्यासाठी लॉगिन करा →",
    claimed: "✓ घेतले!",
    lang_btn: "भाषा",
    sidebar_hero: "मुख्य", sidebar_how: "कसे", sidebar_listings: "यादी",
    sidebar_why: "का", sidebar_stories: "कहाण्या", sidebar_cta: "सामील",
    sidebar_theme: "थीम",
    loc_popup_title: "पत्ता भरा",
    loc_popup_sub: "तुमचा पत्ता कसा भरायचा?",
    loc_auto: "📍 सध्याचे स्थान वापरा",
    loc_manual: "✏️ स्वतः भरा",
    loc_fetching: "स्थान मिळवत आहे…",
    loc_error: "स्थान मिळाले नाही. कृपया स्वतः भरा.",
    city_placeholder: "शहर शोधा…",
    phone_placeholder: "फोन नंबर",
    step1: "मूलभूत माहिती", step2_donor: "PG तपशील", step2_recv: "प्राधान्ये", step3: "पुनरावलोकन",
    full_address: "पूर्ण पत्ता",
    pg_name: "PG / हॉस्टेलचे नाव",
    city_label: "शहर",
    state_label: "राज्य",
    diet_label: "जेवणाचा प्रकार",
    create_account: "खाते तयार करा 🎉",
  },
  es: {
    brand: "ResQMeal",
    nav_home: "Inicio", nav_about: "Acerca de", nav_contact: "Contacto",
    nav_donate: "+ Donar Comida", nav_logout: "Cerrar sesión", nav_register: "Registrarse", nav_login: "Iniciar sesión",
    hero_label: "ANUNCIOS EN VIVO CERCA DE TI",
    hero_title1: "Rescata comida sobrante.",
    hero_title2: "Alimenta a alguien hoy.",
    hero_sub: "Conéctate con PGs y hostales para reclamar comidas gratuitas antes de que se desperdicien. 🍱",
    btn_browse: "Ver Anuncios →",
    btn_list: "Listar Comida Sobrante",
    how_label: "CÓMO FUNCIONA",
    how_title: "Tres pasos para cero desperdicio",
    listings_label: "DISPONIBLE AHORA",
    listings_title: "Excedentes cerca de ti",
    why_label: "POR QUÉ RESQMEAL",
    why_title: "Creado para la cultura de hostales",
    stories_label: "HISTORIAS",
    stories_title: "Lo que dicen las personas",
    cta_label: "ÚNETE AL MOVIMIENTO",
    cta_title: "Cada comida rescatada",
    cta_green: "importa.",
    cta_sub: "Ya seas dueño de un PG o alguien buscando comida — aquí perteneces.",
    btn_get_started: "Empezar Gratis →",
    btn_learn: "Conoce Nuestra Misión",
    btn_dashboard: "Ir al Panel →",
    login_welcome: "BIENVENIDO DE VUELTA",
    login_title: "Inicia sesión en",
    login_sub: "¿Nuevo aquí?",
    login_create: "Crear una cuenta →",
    login_email: "Correo electrónico",
    login_pass: "Contraseña",
    login_forgot: "¿Olvidaste tu contraseña?",
    login_remember: "Recuérdame 30 días",
    login_btn: "Iniciar sesión →",
    register_label: "CREAR CUENTA",
    register_title: "Únete a",
    register_sub: "¿Ya tienes una cuenta?",
    register_signin: "Iniciar sesión →",
    search_placeholder: "Buscar por título o descripción…",
    all_locations: "Todos los lugares",
    claim_btn: "Reclamar Comida →",
    login_to_claim: "Inicia sesión para reclamar →",
    claimed: "✓ ¡Reclamado!",
    lang_btn: "Idioma",
    sidebar_hero: "Inicio", sidebar_how: "Cómo", sidebar_listings: "Anuncios",
    sidebar_why: "Por qué", sidebar_stories: "Historias", sidebar_cta: "Únete",
    sidebar_theme: "Temas",
    loc_popup_title: "Rellenar Dirección",
    loc_popup_sub: "¿Cómo deseas rellenar tu dirección?",
    loc_auto: "📍 Usar mi ubicación actual",
    loc_manual: "✏️ Rellenar manualmente",
    loc_fetching: "Obteniendo ubicación…",
    loc_error: "No se pudo obtener la ubicación. Rellena manualmente.",
    city_placeholder: "Buscar ciudad…",
    phone_placeholder: "Número de teléfono",
    step1: "Información básica", step2_donor: "Detalles PG", step2_recv: "Preferencias", step3: "Revisión",
    full_address: "Dirección completa",
    pg_name: "Nombre del PG / Hostal",
    city_label: "Ciudad",
    state_label: "Estado",
    diet_label: "Tipo de comida habitual",
    create_account: "Crear Cuenta 🎉",
  },
  fr: {
    brand: "ResQMeal",
    nav_home: "Accueil", nav_about: "À propos", nav_contact: "Contact",
    nav_donate: "+ Donner un repas", nav_logout: "Déconnexion", nav_register: "S'inscrire", nav_login: "Connexion",
    hero_label: "ANNONCES EN DIRECT PRÈS DE VOUS",
    hero_title1: "Sauvez les repas excédentaires.",
    hero_title2: "Nourrissez quelqu'un aujourd'hui.",
    hero_sub: "Connectez-vous avec des PGs et des auberges pour réclamer des repas gratuits avant qu'ils ne soient gaspillés. 🍱",
    btn_browse: "Voir les Annonces →",
    btn_list: "Lister les Surplus",
    how_label: "COMMENT ÇA MARCHE",
    how_title: "Trois étapes pour zéro déchet",
    listings_label: "DISPONIBLE MAINTENANT",
    listings_title: "Surplus près de chez vous",
    why_label: "POURQUOI RESQMEAL",
    why_title: "Conçu pour la culture des auberges",
    stories_label: "TÉMOIGNAGES",
    stories_title: "Ce que les gens disent",
    cta_label: "REJOIGNEZ LE MOUVEMENT",
    cta_title: "Chaque repas sauvé",
    cta_green: "compte.",
    cta_sub: "Que vous soyez propriétaire d'un PG ou à la recherche d'un repas — vous êtes le bienvenu.",
    btn_get_started: "Commencer Gratuitement →",
    btn_learn: "Notre Mission",
    btn_dashboard: "Aller au tableau de bord →",
    login_welcome: "BON RETOUR",
    login_title: "Connectez-vous à",
    login_sub: "Nouveau ici ?",
    login_create: "Créer un compte →",
    login_email: "Adresse e-mail",
    login_pass: "Mot de passe",
    login_forgot: "Mot de passe oublié ?",
    login_remember: "Se souvenir de moi 30 jours",
    login_btn: "Se connecter →",
    register_label: "CRÉER UN COMPTE",
    register_title: "Rejoignez",
    register_sub: "Vous avez déjà un compte ?",
    register_signin: "Se connecter →",
    search_placeholder: "Rechercher par titre ou description…",
    all_locations: "Tous les lieux",
    claim_btn: "Réclamer le repas →",
    login_to_claim: "Connectez-vous pour réclamer →",
    claimed: "✓ Réclamé !",
    lang_btn: "Langue",
    sidebar_hero: "Accueil", sidebar_how: "Comment", sidebar_listings: "Annonces",
    sidebar_why: "Pourquoi", sidebar_stories: "Témoignages", sidebar_cta: "Rejoindre",
    sidebar_theme: "Thèmes",
    loc_popup_title: "Remplir l'adresse",
    loc_popup_sub: "Comment souhaitez-vous remplir votre adresse ?",
    loc_auto: "📍 Utiliser ma position actuelle",
    loc_manual: "✏️ Remplir manuellement",
    loc_fetching: "Récupération de la position…",
    loc_error: "Impossible de récupérer la position. Veuillez remplir manuellement.",
    city_placeholder: "Rechercher une ville…",
    phone_placeholder: "Numéro de téléphone",
    step1: "Informations de base", step2_donor: "Détails PG", step2_recv: "Préférences", step3: "Révision",
    full_address: "Adresse complète",
    pg_name: "Nom du PG / Auberge",
    city_label: "Ville",
    state_label: "État",
    diet_label: "Type d'alimentation habituel",
    create_account: "Créer un compte 🎉",
  },
  ar: {
    brand: "ResQMeal",
    nav_home: "الرئيسية", nav_about: "عننا", nav_contact: "اتصل بنا",
    nav_donate: "+ تبرع بوجبة", nav_logout: "تسجيل الخروج", nav_register: "التسجيل", nav_login: "تسجيل الدخول",
    hero_label: "قوائم مباشرة بالقرب منك",
    hero_title1: "أنقذ الطعام الفائض.",
    hero_title2: "أطعم شخصاً اليوم.",
    hero_sub: "تواصل مع المساكن للحصول على وجبات مجانية قبل أن تضيع. 🍱",
    btn_browse: "تصفح القوائم →",
    btn_list: "قائمة الطعام الفائض",
    how_label: "كيف يعمل",
    how_title: "ثلاث خطوات لصفر هدر",
    listings_label: "متاح الآن",
    listings_title: "فائض بالقرب منك",
    why_label: "لماذا ResQMeal",
    why_title: "مبني لثقافة المساكن",
    stories_label: "قصص",
    stories_title: "ما يقوله الناس",
    cta_label: "انضم إلى الحركة",
    cta_title: "كل وجبة ينقذها",
    cta_green: "مهمة.",
    cta_sub: "سواء كنت مالك مسكن أو تبحث عن وجبة — أنت تنتمي هنا.",
    btn_get_started: "ابدأ مجاناً →",
    btn_learn: "تعرف على مهمتنا",
    btn_dashboard: "الذهاب إلى لوحة التحكم →",
    login_welcome: "أهلاً بعودتك",
    login_title: "تسجيل الدخول إلى",
    login_sub: "جديد هنا؟",
    login_create: "إنشاء حساب →",
    login_email: "البريد الإلكتروني",
    login_pass: "كلمة المرور",
    login_forgot: "نسيت كلمة المرور؟",
    login_remember: "تذكرني لمدة 30 يوماً",
    login_btn: "تسجيل الدخول →",
    register_label: "إنشاء حساب",
    register_title: "انضم إلى",
    register_sub: "لديك حساب بالفعل؟",
    register_signin: "تسجيل الدخول →",
    search_placeholder: "البحث بالعنوان أو الوصف…",
    all_locations: "جميع المواقع",
    claim_btn: "احصل على الوجبة →",
    login_to_claim: "تسجيل الدخول للحصول →",
    claimed: "✓ تم الحصول!",
    lang_btn: "اللغة",
    sidebar_hero: "الرئيسية", sidebar_how: "كيف", sidebar_listings: "القوائم",
    sidebar_why: "لماذا", sidebar_stories: "قصص", sidebar_cta: "انضم",
    sidebar_theme: "ثيمات",
    loc_popup_title: "ملء العنوان",
    loc_popup_sub: "كيف تريد ملء عنوانك؟",
    loc_auto: "📍 استخدم موقعي الحالي",
    loc_manual: "✏️ ملء يدوي",
    loc_fetching: "جارٍ الحصول على الموقع…",
    loc_error: "تعذر الحصول على الموقع. يرجى الملء يدوياً.",
    city_placeholder: "ابحث عن مدينة…",
    phone_placeholder: "رقم الهاتف",
    step1: "المعلومات الأساسية", step2_donor: "تفاصيل المسكن", step2_recv: "التفضيلات", step3: "المراجعة",
    full_address: "العنوان الكامل",
    pg_name: "اسم المسكن",
    city_label: "المدينة",
    state_label: "الولاية",
    diet_label: "نوع الطعام المعتاد",
    create_account: "إنشاء حساب 🎉",
  },
};

const LANG_META = {
  en: { label: "English",  flag: "🇬🇧" },
  hi: { label: "हिंदी",    flag: "🇮🇳" },
  mr: { label: "मराठी",   flag: "🇮🇳" },
  es: { label: "Español",  flag: "🇪🇸" },
  fr: { label: "Français", flag: "🇫🇷" },
  ar: { label: "العربية",  flag: "🇸🇦" },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("resqmeal_lang") || "en");

  useEffect(() => {
    localStorage.setItem("resqmeal_lang", lang);
    document.documentElement.setAttribute("dir", lang === "ar" ? "rtl" : "ltr");
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t, LANG_META, translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
}
